"""removed that model

Revision ID: 45284a1e217f
Revises: f01a11e00de0
Create Date: 2025-07-09 22:43:39.342925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '45284a1e217f'
down_revision = 'f01a11e00de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('request_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('requested_by', sa.INTEGER(), nullable=False),
    sa.Column('request_data', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['organizers.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['management.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
